# Docker Compose 파일 버전을 명시합니다. 여기서는 버전 3.8을 사용합니다.
version: '3.8'

# services 섹션은 실행할 개별 서비스를 정의합니다.
services:
  # 첫 번째 Zookeeper 인스턴스를 정의합니다.
  my-zookeeper-1:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: my-zookeeper-1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 20
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_electionPortBindRetry: 20
      ZOOKEEPER_SERVERS: |
        server.2=my-zookeeper-2:2888:3888
        server.3=my-zookeeper-3:2888:3888
        server.1=my-zookeeper-1:2888:3888

  # 두 번째 Zookeeper 인스턴스를 정의합니다.
  my-zookeeper-2:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: my-zookeeper-2
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 20
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_electionPortBindRetry: 20
      ZOOKEEPER_SERVERS: |
        server.1=my-zookeeper-1:2888:3888
        server.2=my-zookeeper-2:2888:3888
        server.3=my-zookeeper-3:2888:3888

  # 세 번째 Zookeeper 인스턴스를 정의합니다.
  my-zookeeper-3:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: my-zookeeper-3
    ports:
      - "2183:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 20
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_electionPortBindRetry: 20
      ZOOKEEPER_SERVERS: |
        server.1=my-zookeeper-1:2888:3888
        server.2=my-zookeeper-2:2888:3888
        server.3=my-zookeeper-3:2888:3888


  # 첫 번째 Kafka 브로커를 정의합니다.
  kafka-broker-1:
    # 사용할 도커 이미지와 버전을 명시합니다. 여기서는 confluentinc/cp-kafka 이미지의 최신 버전을 사용합니다.
    image: confluentinc/cp-kafka:7.0.1
    # 호스트 이름을 설정합니다.
    hostname: kafka-broker-1
    # 호스트와 컨테이너 간의 포트 매핑을 설정합니다. 여기서는 호스트의 9092 포트를 컨테이너의 9092 포트에 매핑합니다.
    ports:
      - "9092:9092"
    # 컨테이너의 환경 변수를 설정합니다.
    environment:
      # Kafka 브로커의 고유 ID를 설정합니다.
      KAFKA_BROKER_ID: 1
      # Kafka 브로커가 연결할 Zookeeper 서버 목록을 설정합니다.
      KAFKA_ZOOKEEPER_CONNECT: my-zookeeper-1:2181,my-zookeeper-2:2181,my-zookeeper-3:2181
      # Kafka 브로커의 광고된 리스너 주소를 설정합니다.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092
      # Kafka 브로커의 리스너 주소를 설정합니다.
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      # 오프셋 토픽의 복제 인자 수를 설정합니다. 복제 인자가 3인 이유는 데이터의 안정성과 가용성을 높이기 위함입니다.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    # 의존성을 설정하여 Zookeeper가 먼저 시작되도록 합니다.
    depends_on:
      - my-zookeeper-1
      - my-zookeeper-2
      - my-zookeeper-3

  # 두 번째 Kafka 브로커를 정의합니다.
  kafka-broker-2:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka-broker-2
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: my-zookeeper-1:2181,my-zookeeper-2:2181,my-zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    depends_on:
      - my-zookeeper-1
      - my-zookeeper-2
      - my-zookeeper-3

  # 세 번째 Kafka 브로커를 정의합니다.
  kafka-broker-3:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka-broker-3
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: my-zookeeper-1:2181,my-zookeeper-2:2181,my-zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    depends_on:
      - my-zookeeper-1
      - my-zookeeper-2
      - my-zookeeper-3

# 네트워크 설정을 정의해, 모든 서비스가 동일한 네트워크를 공유하도록 합니다.
networks:
  default:
    name: kafka-network
