spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:39093,localhost:49094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
      properties:
        heartbeat.interval.ms: 1000  # heartbeat 간격을 1초로 설정
        session.timeout.ms: 15000    # session timeout을 15초로 설정
        max.poll.interval.ms: 300000 # 최대 poll 간격을 5분으로 설정
    listener:
      poll-timeout: 3000
      ack-mode: MANUAL
      missing-topics-fatal: false
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/test_database
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
logging:
  level:
    org:
      apache:
        kafka: INFO
      hibernate:
        SQL: DEBUG
      orm:
        jdbc:
          bind: TRACE
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
